name: AIO

on:
 - push

# global env -----------------------------------------------------------
# update for current release
# revision has form:
# for beta: 0.N = beta N  (0.0 is first beta, then 0.1 ...)
# for release: N = 1, 2, 3 ...
env:
  target: j9.4_win64.exe
  targets: j9.4_win64_slim.exe
  revision: 0.12

jobs:

# windows --------------------------------------------------------------
 winaio:
  name: WinAIO
  runs-on: windows-latest
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v2
     env:
        password: ${{ secrets.PASSWORD }}
        url: https://github.com/${{github.repository}}

   - name: Get files
     shell: pwsh
     run: |
      .\getfiles.ps1 ${{ env.target }} ${{ env.revision }}

   - name: Build AIO
     uses: joncloud/makensis-action@v4

   - name: Release WinAIO
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: "${{ env.target }},revision.txt,version.txt"
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true

# windows slim ---------------------------------------------------------
 winaios:
  name: WinAIOslim
  runs-on: windows-latest
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v2
     env:
        password: ${{ secrets.PASSWORD }}
        url: https://github.com/${{github.repository}}

   - name: Get files
     shell: pwsh
     run: |
      .\getfiles.ps1 ${{ env.targets }} ${{ env.revision }}

   - name: Build AIO
     uses: joncloud/makensis-action@v4

   - name: Release WinAIO
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: ${{ env.targets }}
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true

# webhook --------------------------------------------------------------
 webhook:
  name: Run Webhook
  runs-on: ubuntu-latest
  needs: [winaio, winaios]
  steps:
   - name: update server
     uses: distributhor/workflow-webhook@v2
     env:
      webhook_url: ${{ secrets.WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      data: '{ "id": "${{ env.target }}" }'
