name: AIO

on:
 - push

jobs:

# windows --------------------------------------------------------------
 winaio:
  name: WinAIO
  runs-on: windows-latest
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v2
     env:
        password: ${{ secrets.PASSWORD }}
        url: https://github.com/${{github.repository}}

   - name: Get version
     shell: pwsh
     run: .\getversion.ps1

   - name: Get files
     shell: pwsh
     run: .\getfiles.ps1 0

   - name: Get target
     id: read_file
     uses: andstor/file-reader-action@v1
     with:
      path: "target.txt"

   - name: Build AIO
     uses: joncloud/makensis-action@v4

   - name: Release WinAIO
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: "${{ steps.read_file.outputs.contents }},revision.txt,version.txt"
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true

# windows slim ---------------------------------------------------------
 winaios:
  name: WinAIOslim
  runs-on: windows-latest
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v2
     env:
        password: ${{ secrets.PASSWORD }}
        url: https://github.com/${{github.repository}}

   - name: Get version
     shell: pwsh
     run: .\getversion.ps1

   - name: Get files
     shell: pwsh
     run: .\getfiles.ps1 1

   - name: Get target
     id: read_file
     uses: andstor/file-reader-action@v1
     with:
      path: "targets.txt"

   - name: Build AIO
     uses: joncloud/makensis-action@v4

   - name: Release WinAIO
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: "${{ steps.read_file.outputs.contents }}"
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true

# webhook --------------------------------------------------------------
 webhook:
  name: Run Webhook
  runs-on: ubuntu-latest
  needs: [winaio, winaios]
  steps:
   - name: update server
     uses: distributhor/workflow-webhook@v2
     env:
      webhook_url: ${{ secrets.WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      data: '{ "id": "${{ env.target }}" }'
