name: AIO

on:
 - push

env:
  target: j904_win64.exe

jobs:

# windows --------------------------------------------------------------
 winaio:
  name: WinAIO
  runs-on: windows-latest
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v2
     env:
        password: ${{ secrets.PASSWORD }}
        url: https://github.com/${{github.repository}}

   - name: Get files
     shell: pwsh
     run: |
      .\getfiles.ps1 ${{ env.target }}

   - name: Build AIO
     uses: joncloud/makensis-action@v4

   - name: Release WinAIO
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: ${{ env.target }}
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true

 webhook:
  name: Run Webhook
  runs-on: ubuntu-latest
  needs: winaio
  steps:
   - name: update server
     uses: distributhor/workflow-webhook@v2
     env:
      webhook_url: ${{ secrets.WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      data: '{ "id": "winaio" }'
